name: phpunit

on: [ push, pull_request ]

permissions: read-all

jobs:
    laravel:
        strategy:
            fail-fast: true
            matrix:
                os: [ "ubuntu", "macos" ]
                php: [ "8.1", "8.2", "8.3", "8.4" ]
                laravel: [ "10.0", "11.0", "12.0" ]
                exclude:
                    - laravel: "11.0"
                      php: "8.1"
                    - laravel: "12.0"
                      php: "8.1"
                      
        runs-on: ${{ matrix.os }}-latest

        name: OS ${{ matrix.os }}, PHP ${{ matrix.php }}, LRV ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install dependencies
                run: composer require laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
